### ISSUE TITLE
General to-do/idea list

### ISSUE THREAD

**Issue by lazovich** [lazovich/PhdThesis#3]
- [x] REWRITE INTRODUCTION

Chapter 1
- [x] Add more about Higgs xsec calculation details and uncertainties?
- [x] Add references to different NNLO etc. Higgs cross section papers
- [x] Add references to CP3-origins files used for MadGraph RSG calculations: http://cp3-origins.dk/research/units/ed-tools
- [x] Add formula for branching ratios valid for off shell W/Z too (from http://arxiv.org/pdf/hep-ph/0503172v2.pdf)
- [x] Invert order of ttH and bbH cross sections in table

Chapter 5
- [x] ~~Add formula for dijet mass as a function of rapidity difference and jet pT (to explain why having forward jets leads to large Mjj)?~~
- [x] ~~Detailed description of trigger scale factor application?~~
- [x] ~~Add comparison of different ttbar generators in VBF?~~
- [x] Add plots of mT separated into the two Mjj bins!
- [x] Table of cut values
- [x] Split table 5.7 into two smaller tables

Chapter 6
- [x] Add dedicated sub-section on same flavor results

Chapter 7
- [x] Add reference to appendix and put b-tagging WP optimization there
- [x] Cutflow table?
- [x] ~~Appendix on background validation?~~
- [ ] Add b-tagging systematic plots for 3b vs. 4b comparison
